// COPY THIS FILE to keys.h

#define FACEBOOK_APP_KEY @"TOKEN_HERE"

#define BUFFER_CLIENT_ID @"TOKEN_HERE"
#define BUFFER_CLIENT_SECRET @"TOKEN_HERE"

#define LINKEDIN_CLIENT_ID @"TOKEN_HERE"
#define LINKEDIN_CLIENT_SECRET @"TOKEN_HERE"

#define TUMBLR_CLIENT_ID @"TOKEN_HERE"
#define TUMBLR_CLIENT_SECRET @"TOKEN_HERE"

#define ADN_CLIENT_ID @"TOKEN_HERE"
#define ADN_PASSWORD_GRANT_SECRET @"TOKEN_HERE"